# Generated by Django 5.2.5 on 2025-08-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('lead', 'Tech Lead')], default='employee', max_length=10),
        ),
    ]
