# Generated by Django 5.2.5 on 2025-08-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ManyToManyField(to='standup.employeeproject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standup.project')),
            ],
        ),
    ]
