# Generated by Django 5.2.5 on 2025-08-20 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0005_projectassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='employee',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
