# Generated by Django 5.2.5 on 2025-08-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0006_alter_projectassignment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('lead', 'Tech Lead')], max_length=10, null=True),
        ),
    ]
