# Generated by Django 5.2.5 on 2025-08-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0007_user_is_approved_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
