# Generated by Django 5.2.5 on 2025-08-22 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0008_user_is_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile', models.FileField(upload_to='')),
                ('dob', models.DateField(blank=True, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
