# Generated by Django 5.2.5 on 2025-08-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0009_empprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empprofile',
            old_name='users',
            new_name='user',
        ),
    ]
