# Generated by Django 5.2.5 on 2025-08-23 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0010_rename_users_empprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('task_date', models.DateField(default=django.utils.timezone.localdate)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standup.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
