# Generated by Django 5.2.5 on 2025-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0011_dailyupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdates',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dailyupdates',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
