# Generated by Django 5.2.5 on 2025-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0013_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
