# Generated by Django 5.2.5 on 2025-08-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0014_alter_meeting_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
